### ISSUE TITLE
The dataset seems to be different from the paper

### ISSUE THREAD

**Issue by Mukosame** [sysu-imsl/SketchyCOCO#3]
Thanks for contributing this nice dataset! Here I have some small questions about the dataset:

- the index of each category is not continuous, which seems to be different from what used in https://github.com/sysu-imsl/EdgeGAN

- number of images. Taking "cars" as example, the paper shows that there are 683/55 pairwise images, and the readme of this repo shows 411, while in the downloaded dataset, there're 1094 pairs of images just in the training folder. Is there something wrong about the uploaded data?

**Comment by MikeXuQ** [comment]
Thanks for your reminder. You can use the following map to map the index of category to the dataset. And the index of the dataset corresponds to the MS COCO.
model_to_dataset = {
	'0': '5',
	'1': '17',
	'2': '25',
	'3': '24',
	'4': '18',
	'5': '22',
	'6': '11',
	'7': '19',
	'8': '2',
	'9': '3',
	'10': '10',
	'11': '21',
	'13': '4',
	'14': '20',
}
And the readme of this repo only shows the augmentation of the dataset, not the number of the total dataset.

**Comment by Mukosame** [comment]
Thanks for providing the index map. How about the number of images in the provided dataset and the paper? It seems that we can download more images than the paper claims.

**Comment by MikeXuQ** [comment]
We increase 4662 images for 9 objects based on the dataset of the paper version as we claim in this repo. So there is more images than the paper claims.

**Comment by Mukosame** [comment]
Thanks for answering my question!
